name: NRIME
options:
  bundleIdPrefix: com.nrime.inputmethod
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

packages:
  SwiftProtobuf:
    url: https://github.com/apple/swift-protobuf.git
    from: "1.28.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  NRIME:
    type: application
    platform: macOS
    sources:
      - path: NRIME
        excludes:
          - Resources/Info.plist
          - Resources/mozc_server
      - path: NRIME/Resources/mozc_server
        buildPhase: resources
        type: file
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nrime.inputmethod.app
        INFOPLIST_FILE: NRIME/Resources/Info.plist
        INSTALL_PATH: /Library/Input Methods
        SKIP_INSTALL: false
        # LSUIElement is set in Info.plist (allows NSStatusItem + windows)
        PRODUCT_NAME: NRIME
        COMBINE_HIDPI_IMAGES: true
        SWIFT_OBJC_BRIDGING_HEADER: NRIME/NRIME-Bridging-Header.h
        # No @main — we use main.swift
        # Disable automatic code signing for input methods
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_ALLOWED: false
    dependencies:
      - framework: InputMethodKit.framework
        embed: false
      - sdk: Carbon.framework
      - sdk: libsqlite3.tbd
      - package: SwiftProtobuf

  NRIMESettings:
    type: application
    platform: macOS
    sources:
      - path: NRIMESettings
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nrime.settings
        GENERATE_INFOPLIST_FILE: true
        PRODUCT_NAME: NRIMESettings
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_ALLOWED: false
        MACOSX_DEPLOYMENT_TARGET: "13.0"
    info:
      path: NRIMESettings/Info.plist
      properties:
        LSUIElement: true
    dependencies: []

  NRIMETests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: NRIMETests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nrime.inputmethod.app.tests
        GENERATE_INFOPLIST_FILE: true
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_ALLOWED: false
    dependencies:
      - target: NRIME
