// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: protocol/engine_builder.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2010-2021, Google Inc.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//     * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//     * Neither the name of Google Inc. nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Mozc_EngineReloadRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Path to the data file to be loaded in a new engine.
  var filePath: String {
    get {_filePath ?? String()}
    set {_filePath = newValue}
  }
  /// Returns true if `filePath` has been explicitly set.
  var hasFilePath: Bool {self._filePath != nil}
  /// Clears the value of `filePath`. Subsequent reads from it will return its default value.
  mutating func clearFilePath() {self._filePath = nil}

  /// Explicitly specifies the magic number to be used for data validation.
  /// Since acceptable magic number is embedded in Mozc server, this option is
  /// unnecessary for normal cases.  However, this is required for some unit
  /// tests as test data has a different magic number.
  var magicNumber: String {
    get {_magicNumber ?? String()}
    set {_magicNumber = newValue}
  }
  /// Returns true if `magicNumber` has been explicitly set.
  var hasMagicNumber: Bool {self._magicNumber != nil}
  /// Clears the value of `magicNumber`. Subsequent reads from it will return its default value.
  mutating func clearMagicNumber() {self._magicNumber = nil}

  /// Priority of the request (smaller is more prioritized).
  /// The decoder keeps all the requests, and uses the most prioritized one.
  /// For the same priority request, later one overrides existing one.
  /// Effective only with CommandType.SEND_ENGINE_RELOAD_REQUEST.
  var priority: Int32 {
    get {_priority ?? 0}
    set {_priority = newValue}
  }
  /// Returns true if `priority` has been explicitly set.
  var hasPriority: Bool {self._priority != nil}
  /// Clears the value of `priority`. Subsequent reads from it will return its default value.
  mutating func clearPriority() {self._priority = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _filePath: String? = nil
  fileprivate var _magicNumber: String? = nil
  fileprivate var _priority: Int32? = nil
}

struct Mozc_EngineReloadResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var status: Mozc_EngineReloadResponse.Status {
    get {_status ?? .accepted}
    set {_status = newValue}
  }
  /// Returns true if `status` has been explicitly set.
  var hasStatus: Bool {self._status != nil}
  /// Clears the value of `status`. Subsequent reads from it will return its default value.
  mutating func clearStatus() {self._status = nil}

  /// The original request is copied in response for convenience (the reload
  /// command runs asynchronously but client doesn't need to keep the original
  /// request).
  var request: Mozc_EngineReloadRequest {
    get {_request ?? Mozc_EngineReloadRequest()}
    set {_request = newValue}
  }
  /// Returns true if `request` has been explicitly set.
  var hasRequest: Bool {self._request != nil}
  /// Clears the value of `request`. Subsequent reads from it will return its default value.
  mutating func clearRequest() {self._request = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum Status: Int, SwiftProtobuf.Enum, Swift.CaseIterable {

    /// Reload command is accepted.
    case accepted = 0

    /// New data is verified and ready.
    case reloadReady = 1

    /// Engine was replaced by a new instance.
    case reloaded = 2

    /// Failed to start reload because another reload job is currently running.
    case alreadyRunning = 3

    /// Errors in data file.
    case engineVersionMismatch = 4
    case dataMissing = 5
    case dataBroken = 6

    /// File doesn't exist or underlying memory mapping failed.
    case mmapFailure = 7
    case unknownError = 9

    init() {
      self = .accepted
    }

  }

  init() {}

  fileprivate var _status: Mozc_EngineReloadResponse.Status? = nil
  fileprivate var _request: Mozc_EngineReloadRequest? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "mozc"

extension Mozc_EngineReloadRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".EngineReloadRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{4}\u{2}file_path\0\u{4}\u{2}magic_number\0\u{1}priority\0\u{c}\u{1}\u{1}\u{c}\u{3}\u{1}")

  public var isInitialized: Bool {
    if self._filePath == nil {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeSingularStringField(value: &self._filePath) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._magicNumber) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self._priority) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._filePath {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._magicNumber {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._priority {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Mozc_EngineReloadRequest, rhs: Mozc_EngineReloadRequest) -> Bool {
    if lhs._filePath != rhs._filePath {return false}
    if lhs._magicNumber != rhs._magicNumber {return false}
    if lhs._priority != rhs._priority {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Mozc_EngineReloadResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".EngineReloadResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}status\0\u{1}request\0")

  public var isInitialized: Bool {
    if self._status == nil {return false}
    if let v = self._request, !v.isInitialized {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._status) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._request) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._status {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._request {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Mozc_EngineReloadResponse, rhs: Mozc_EngineReloadResponse) -> Bool {
    if lhs._status != rhs._status {return false}
    if lhs._request != rhs._request {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Mozc_EngineReloadResponse.Status: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0ACCEPTED\0\u{1}RELOAD_READY\0\u{1}RELOADED\0\u{1}ALREADY_RUNNING\0\u{1}ENGINE_VERSION_MISMATCH\0\u{1}DATA_MISSING\0\u{1}DATA_BROKEN\0\u{1}MMAP_FAILURE\0\u{2}\u{2}UNKNOWN_ERROR\0")
}
