// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: protocol/user_dictionary_storage.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2010-2021, Google Inc.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//     * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//     * Neither the name of Google Inc. nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Mozc_UserDictionary_UserDictionary: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// LINT.ThenChange(
  ///     dictionary/user_dictionary_util.cc
  /// )
  /// ID of this dictionary
  var id: UInt64 {
    get {_id ?? 0}
    set {_id = newValue}
  }
  /// Returns true if `id` has been explicitly set.
  var hasID: Bool {self._id != nil}
  /// Clears the value of `id`. Subsequent reads from it will return its default value.
  mutating func clearID() {self._id = nil}

  /// name of dictionary
  var name: String {
    get {_name ?? String()}
    set {_name = newValue}
  }
  /// Returns true if `name` has been explicitly set.
  var hasName: Bool {self._name != nil}
  /// Clears the value of `name`. Subsequent reads from it will return its default value.
  mutating func clearName() {self._name = nil}

  var entries: [Mozc_UserDictionary_UserDictionary.Entry] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  /// LINT.IfChange
  enum PosType: Int, SwiftProtobuf.Enum, Swift.CaseIterable {

    /// Use this when the POS tag is not provided or unknown.
    case noPos = 0

    /// "名詞"
    case noun = 1

    /// "短縮よみ"
    case abbreviation = 2

    /// "サジェストのみ"
    case suggestionOnly = 3

    /// "固有名詞"
    case properNoun = 4

    /// "人名"
    case personalName = 5

    /// "姓"
    case familyName = 6

    /// "名"
    case firstName = 7

    /// "組織"
    case organizationName = 8

    /// "地名"
    case placeName = 9

    /// "名詞サ変"
    case saIrregularConjugationNoun = 10

    /// "名詞形動"
    case adjectiveVerbalNoun = 11

    /// "数"
    case number = 12

    /// "アルファベット"
    case alphabet = 13

    /// "記号"
    case symbol = 14

    /// "顔文字"
    case emoticon = 15

    /// "副詞"
    case adverb = 16

    /// "連体詞"
    case prenounAdjectival = 17

    /// "接続詞"
    case conjunction = 18

    /// "感動詞"
    case interjection = 19

    /// "接頭語"
    case prefix = 20

    /// "助数詞"
    case counterSuffix = 21

    /// "接尾一般"
    case genericSuffix = 22

    /// "接尾人名"
    case personNameSuffix = 23

    /// "接尾地名"
    case placeNameSuffix = 24

    /// "動詞ワ行五段"
    case waGroup1Verb = 25

    /// "動詞カ行五段"
    case kaGroup1Verb = 26

    /// "動詞サ行五段"
    case saGroup1Verb = 27

    /// "動詞タ行五段"
    case taGroup1Verb = 28

    /// "動詞ナ行五段"
    case naGroup1Verb = 29

    /// "動詞マ行五段"
    case maGroup1Verb = 30

    /// "動詞ラ行五段"
    case raGroup1Verb = 31

    /// "動詞ガ行五段"
    case gaGroup1Verb = 32

    /// "動詞バ行五段"
    case baGroup1Verb = 33

    /// "動詞ハ行四段"
    case haGroup1Verb = 34

    /// "動詞一段"
    case group2Verb = 35

    /// "動詞カ変"
    case kuruGroup3Verb = 36

    /// "動詞サ変"
    case suruGroup3Verb = 37

    /// "動詞ザ変"
    case zuruGroup3Verb = 38

    /// "動詞ラ変"
    case ruGroup3Verb = 39

    /// "形容詞"
    case adjective = 40

    /// "終助詞"
    case sentenceEndingParticle = 41

    /// "句読点"
    case punctuation = 42

    /// "独立語"
    case freeStandingWord = 43

    /// "抑制単語"
    case suppressionWord = 44

    init() {
      self = .noPos
    }

  }

  /// entry of each word
  struct Entry: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var key: String {
      get {_key ?? String()}
      set {_key = newValue}
    }
    /// Returns true if `key` has been explicitly set.
    var hasKey: Bool {self._key != nil}
    /// Clears the value of `key`. Subsequent reads from it will return its default value.
    mutating func clearKey() {self._key = nil}

    var value: String {
      get {_value ?? String()}
      set {_value = newValue}
    }
    /// Returns true if `value` has been explicitly set.
    var hasValue: Bool {self._value != nil}
    /// Clears the value of `value`. Subsequent reads from it will return its default value.
    mutating func clearValue() {self._value = nil}

    var comment: String {
      get {_comment ?? String()}
      set {_comment = newValue}
    }
    /// Returns true if `comment` has been explicitly set.
    var hasComment: Bool {self._comment != nil}
    /// Clears the value of `comment`. Subsequent reads from it will return its default value.
    mutating func clearComment() {self._comment = nil}

    /// Historically we used to use tag number '3' for POS in string format.
    /// In order to switch it to enum based POS, we removed (deprecated) the
    /// tag number '3' field and created another field numbered '5'.
    /// Historically the default POS tag was NOUN, and "NO_POS" is added later.
    /// In order to preserve the original default behavior, default POS tag is
    /// explicitly specified as NOUN. However, this can be changed if there is no
    /// problem with "NO_POS".
    var pos: Mozc_UserDictionary_UserDictionary.PosType {
      get {_pos ?? .noun}
      set {_pos = newValue}
    }
    /// Returns true if `pos` has been explicitly set.
    var hasPos: Bool {self._pos != nil}
    /// Clears the value of `pos`. Subsequent reads from it will return its default value.
    mutating func clearPos() {self._pos = nil}

    /// In multilingual settings, Gboard's personal dictionary will feed entries
    /// with locale information. We can change the behavior (filter or demote)
    /// The locale is usually formatted in BCP47.
    /// In TSV format, the locale is encoded in the POS field as `pos:locale`
    /// "名詞:ja".
    var locale: String {
      get {_locale ?? String()}
      set {_locale = newValue}
    }
    /// Returns true if `locale` has been explicitly set.
    var hasLocale: Bool {self._locale != nil}
    /// Clears the value of `locale`. Subsequent reads from it will return its default value.
    mutating func clearLocale() {self._locale = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _key: String? = nil
    fileprivate var _value: String? = nil
    fileprivate var _comment: String? = nil
    fileprivate var _pos: Mozc_UserDictionary_UserDictionary.PosType? = nil
    fileprivate var _locale: String? = nil
  }

  init() {}

  fileprivate var _id: UInt64? = nil
  fileprivate var _name: String? = nil
}

struct Mozc_UserDictionary_UserDictionaryStorage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// version of user dictionary
  var version: Int32 {
    get {_version ?? 0}
    set {_version = newValue}
  }
  /// Returns true if `version` has been explicitly set.
  var hasVersion: Bool {self._version != nil}
  /// Clears the value of `version`. Subsequent reads from it will return its default value.
  mutating func clearVersion() {self._version = nil}

  /// dictionary body
  var dictionaries: [Mozc_UserDictionary_UserDictionary] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _version: Int32? = nil
}

struct Mozc_UserDictionary_UserDictionaryImportData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var dictionaryName: String {
    get {_dictionaryName ?? String()}
    set {_dictionaryName = newValue}
  }
  /// Returns true if `dictionaryName` has been explicitly set.
  var hasDictionaryName: Bool {self._dictionaryName != nil}
  /// Clears the value of `dictionaryName`. Subsequent reads from it will return its default value.
  mutating func clearDictionaryName() {self._dictionaryName = nil}

  /// TSV data.
  var data: String {
    get {_data ?? String()}
    set {_data = newValue}
  }
  /// Returns true if `data` has been explicitly set.
  var hasData: Bool {self._data != nil}
  /// Clears the value of `data`. Subsequent reads from it will return its default value.
  mutating func clearData() {self._data = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _dictionaryName: String? = nil
  fileprivate var _data: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "mozc.user_dictionary"

extension Mozc_UserDictionary_UserDictionary: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UserDictionary"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{2}\u{2}name\0\u{1}entries\0\u{c}\u{2}\u{1}\u{c}\u{5}\u{1}\u{c}\u{6}\u{1}")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self._id) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._name) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.entries) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._id {
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._name {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    if !self.entries.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.entries, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Mozc_UserDictionary_UserDictionary, rhs: Mozc_UserDictionary_UserDictionary) -> Bool {
    if lhs._id != rhs._id {return false}
    if lhs._name != rhs._name {return false}
    if lhs.entries != rhs.entries {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Mozc_UserDictionary_UserDictionary.PosType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0NO_POS\0\u{1}NOUN\0\u{1}ABBREVIATION\0\u{1}SUGGESTION_ONLY\0\u{1}PROPER_NOUN\0\u{1}PERSONAL_NAME\0\u{1}FAMILY_NAME\0\u{1}FIRST_NAME\0\u{1}ORGANIZATION_NAME\0\u{1}PLACE_NAME\0\u{1}SA_IRREGULAR_CONJUGATION_NOUN\0\u{1}ADJECTIVE_VERBAL_NOUN\0\u{1}NUMBER\0\u{1}ALPHABET\0\u{1}SYMBOL\0\u{1}EMOTICON\0\u{1}ADVERB\0\u{1}PRENOUN_ADJECTIVAL\0\u{1}CONJUNCTION\0\u{1}INTERJECTION\0\u{1}PREFIX\0\u{1}COUNTER_SUFFIX\0\u{1}GENERIC_SUFFIX\0\u{1}PERSON_NAME_SUFFIX\0\u{1}PLACE_NAME_SUFFIX\0\u{1}WA_GROUP1_VERB\0\u{1}KA_GROUP1_VERB\0\u{1}SA_GROUP1_VERB\0\u{1}TA_GROUP1_VERB\0\u{1}NA_GROUP1_VERB\0\u{1}MA_GROUP1_VERB\0\u{1}RA_GROUP1_VERB\0\u{1}GA_GROUP1_VERB\0\u{1}BA_GROUP1_VERB\0\u{1}HA_GROUP1_VERB\0\u{1}GROUP2_VERB\0\u{1}KURU_GROUP3_VERB\0\u{1}SURU_GROUP3_VERB\0\u{1}ZURU_GROUP3_VERB\0\u{1}RU_GROUP3_VERB\0\u{1}ADJECTIVE\0\u{1}SENTENCE_ENDING_PARTICLE\0\u{1}PUNCTUATION\0\u{1}FREE_STANDING_WORD\0\u{1}SUPPRESSION_WORD\0")
}

extension Mozc_UserDictionary_UserDictionary.Entry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Mozc_UserDictionary_UserDictionary.protoMessageName + ".Entry"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}key\0\u{1}value\0\u{2}\u{2}comment\0\u{1}pos\0\u{2}\u{7}locale\0\u{c}\u{3}\u{1}\u{c}\u{a}\u{1}\u{c}\u{b}\u{1}")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._key) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._value) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._comment) }()
      case 5: try { try decoder.decodeSingularEnumField(value: &self._pos) }()
      case 12: try { try decoder.decodeSingularStringField(value: &self._locale) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._key {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._value {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._comment {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._pos {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._locale {
      try visitor.visitSingularStringField(value: v, fieldNumber: 12)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Mozc_UserDictionary_UserDictionary.Entry, rhs: Mozc_UserDictionary_UserDictionary.Entry) -> Bool {
    if lhs._key != rhs._key {return false}
    if lhs._value != rhs._value {return false}
    if lhs._comment != rhs._comment {return false}
    if lhs._pos != rhs._pos {return false}
    if lhs._locale != rhs._locale {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Mozc_UserDictionary_UserDictionaryStorage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UserDictionaryStorage"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}version\0\u{1}dictionaries\0\u{c}\u{a}\u{1}")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._version) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.dictionaries) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._version {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    if !self.dictionaries.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.dictionaries, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Mozc_UserDictionary_UserDictionaryStorage, rhs: Mozc_UserDictionary_UserDictionaryStorage) -> Bool {
    if lhs._version != rhs._version {return false}
    if lhs.dictionaries != rhs.dictionaries {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Mozc_UserDictionary_UserDictionaryImportData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UserDictionaryImportData"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}dictionary_name\0\u{1}data\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._dictionaryName) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._data) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._dictionaryName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._data {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Mozc_UserDictionary_UserDictionaryImportData, rhs: Mozc_UserDictionary_UserDictionaryImportData) -> Bool {
    if lhs._dictionaryName != rhs._dictionaryName {return false}
    if lhs._data != rhs._data {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
